
export const menuItems = [
    {
        id:1,
        text:"consultation",
        link:"/Consultation",
        subMenu:[
            {
                id:1,
                text:"consultationsub1",
                link:"test"
            },
            {
                id:2,
                text:"consultationsub2",
                link:"test"
            },
            {
                id:3,
                text:"consultationsub3",
                link:"test"
            },
            {
                id:4,
                text:"consultationsub4",
                link:"test"
            }
        ]
    },
    {
        id:2,
        text:"transaction",
        link:"/Transaction",
        subMenu:[
            {
                id:1,
                text:"consultationsub1",
                link:"test"
            },
            {
                id:2,
                text:"consultationsub2",
                link:"test"
            },
            {
                id:3,
                text:"consultationsub3",
                link:"test"
            },
            {
                id:4,
                text:"consultationsub4",
                link:"test"
            }
        ]
    },
    {
        id:3,
        text:"Mpc",
        link:"/Mpc",
        subMenu:[]
    }
]