
export const menuItems = [
    {
        id:1,
        text:"consultation",
        link:"test",
        subMenu:[
            {
                id:1,
                text:"consultationsub1",
                link:"test"
            },
            {
                id:1,
                text:"consultationsub2",
                link:"test"
            },
            {
                id:1,
                text:"consultationsub3",
                link:"test"
            },
            {
                id:1,
                text:"consultationsub4",
                link:"test"
            }
        ]
    },
    {
        id:1,
        text:"transaction",
        link:"test",
        subMenu:[
            {
                id:1,
                text:"consultationsub1",
                link:"test"
            },
            {
                id:1,
                text:"consultationsub2",
                link:"test"
            },
            {
                id:1,
                text:"consultationsub3",
                link:"test"
            },
            {
                id:1,
                text:"consultationsub4",
                link:"test"
            }
        ]
    },
    {
        id:1,
        text:"telechargement",
        link:"test",
        subMenu:[]
    }
]